### ISSUE TITLE
/ as part of the value of a URI template variable results in handler not being found

### ISSUE THREAD

**Issue by colin-adams** [EiffelWebFramework/EWF#129]
If I map the following route to a handler:

/mapping/{relationship-name}

then when relationship name is specified as something like:

FROM%20%2F%20TO

The 404 response is:

The requested URL /mapping/FROM / TO was not found on this server.

The lack of generated self-documentation in the result indicates that the handler was not matched.  It would appear that the template value is first percent-decoded, and only then the resultant URL is applied to the router.

**Comment by jocelyn** [comment]
Side note on this old post.
A common workaround is to double percent-encode the value in path.
this way the %20%2F are encoded one more time.
But you need to remember to double unencode them.

On eiffel.org wiki system, this is what is used for wiki page title, that may contain "/" .
I looked at many different solutions, and I found this was the easiest and portable solution.
In fact, we have a special encoding for the wiki page title, and title are percent-encoded once, and the /, \  (and associated percent-encoded value) are encoded once more, just to workaround issue found on apache for instance.
